export default function determineColor(colorState: string | undefined) {
  return colorState === "#000"
    ? "Black"
    : colorState === "#fff"
    ? "White"
    : colorState === "#30323C"
    ? "Gray"
    : colorState === "#F4F4E8"
    ? "Light White"
    : colorState === "#595E7B"
    ? "Gray"
    : colorState === "#181A29"
    ? "Dark"
    : colorState === "#7BB4B5"
    ? "Cyan"
    : colorState === "#FAC0C3"
    ? "Pink"
    : colorState === "#E6B2B8"
    ? "Pink"
    : colorState === "#D1C2AD"
    ? "Brown"
    : colorState === "#E3E2DE"
    ? "Light Gray"
    : colorState === "#FE37A7"
    ? "Pink"
    : colorState === "#2A2A2C"
    ? "Dirt"
    : colorState === "#E9E7E6"
    ? "Light White"
    : colorState === "#46302C"
    ? "Brown"
    : colorState === "#121629"
    ? "Black"
    : colorState === "#B1412C"
    ? "Orange"
    : colorState === "#272429"
    ? "Brown"
    : colorState === "#3D3D56"
    ? "Gray"
    : colorState === "#6C1F31"
    ? "Red"
    : colorState === "#C1C0C9"
    ? "Gray"
    : colorState === "#D9C8B4"
    ? "Brown"
    : colorState === "#94815F"
    ? "Brown"
    : colorState === "#406174"
    ? "Cyan"
    : colorState === "#6A323F"
    ? "Dirt"
    : colorState === "#656D6D"
    ? "Gray"
    : colorState === "#F0C1CB"
    ? "Pink"
    : colorState === "#F6DFA8"
    ? "Brown"
    : colorState === "#F4F4F4"
    ? "Light White"
    : colorState === "#EBEBEB"
    ? "Light White"
    : colorState === "#C1AA84"
    ? "Brown"
    : colorState === "#37313C"
    ? "Dark Brown"
    : colorState === "#E1DED5"
    ? "Light Brown"
    : colorState === "#2A346B"
    ? "Blue"
    : colorState === "#ddd"
    ? "Gray"
    : colorState === "#00FF00"
    ? "Green"
    : colorState === "#ffd500"
    ? "Yellow"
    : "Choose a color";
}
