const determineSize = (sizeState: string | undefined) => {
  return sizeState === "XS"
    ? "Extra Small"
    : sizeState === "S"
    ? "Small"
    : sizeState === "M"
    ? "Medium"
    : sizeState === "L"
    ? "Large"
    : sizeState === "XL"
    ? "Extra Large"
    : sizeState === "freestyle"
    ? "Free Style"
    : sizeState === "33"
    ? "33"
    : sizeState === "34"
    ? "34"
    : sizeState === "35"
    ? "35"
    : sizeState === "36"
    ? "36"
    : sizeState === "37"
    ? "37"
    : sizeState === "38"
    ? "38"
    : sizeState === "39"
    ? "39"
    : sizeState === "40"
    ? "40"
    : sizeState === "4"
    ? "4"
    : sizeState === "6"
    ? "6"
    : sizeState === "8"
    ? "8"
    : sizeState === "10"
    ? "10"
    : "Choose a size";
};

export default determineSize;
